version: '2.1'
volumes:
  resin-data: {}
services:
  ha:
    build:
      context: ./ha
    network_mode: host
    ports:
      - '8123:8123'
    volumes:
      - 'resin-data:/data'
    environment:
      SERVICE_NAME: ha
  nginx:
    build:
      context: ./nginx
    volumes:
      - 'resin-data:/etc'
    ports:
      - '80:80'
